# Generated by Django 6.0 on 2026-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecomm_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('category_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
