# Generated by Django 6.0 on 2026-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200, unique=True)),
                ('destination_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('destination_desc', models.TextField(blank=True, null=True)),
                ('destination_location', models.CharField(max_length=200)),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('destination_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
