# Generated by Django 6.0 on 2026-08-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200, unique=True)),
                ('tour_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tour_desc', models.TextField(blank=True, null=True)),
                ('tour_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField(default=20)),
                ('tour_start_date', models.DateField(blank=True, null=True)),
                ('tour_end_date', models.DateField(blank=True, null=True)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('is_active', models.BooleanField(default=True)),
                ('tour_created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='Travel.destination')),
            ],
        ),
    ]
