# Generated by Django 6.0 on 2026-08-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=200)),
                ('guide_email', models.EmailField(max_length=254, unique=True)),
                ('guide_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guide_photo', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('guide_location', models.CharField(blank=True, max_length=200, null=True)),
                ('guide_languages', models.CharField(blank=True, help_text='Example: English, Hindi, Bengali', max_length=300, null=True)),
                ('guide_experience', models.PositiveIntegerField(default=0, help_text='Experience in years')),
                ('guide_specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('guide_bio', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('guide_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('CAB', 'Cab')], max_length=20)),
                ('operator_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('transport_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('available_seats', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('transport_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_description', models.TextField(blank=True, null=True)),
                ('hotel_address', models.CharField(max_length=300)),
                ('hotel_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hotel_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('available_rooms', models.PositiveIntegerField(default=1)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel_created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Travel.destination')),
            ],
        ),
    ]
