# Generated by Django 6.0 on 2026-08-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_remove_booking_bus_remove_booking_flight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_name',
            new_name='bus_operator',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='bus_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='bus_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_name',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_type',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_class',
        ),
        migrations.AddField(
            model_name='train',
            name='railway_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
