# Generated by Django 6.0 on 2026-08-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0007_rename_bus_name_bus_bus_operator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecomm_Category',
            new_name='Tour_Category',
        ),
    ]
