# Generated by Django 6.0 on 2026-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_booking_bus_booking_flight_booking_selected_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=30),
        ),
    ]
