# Generated by Django 6.0 on 2026-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_mood',
            field=models.CharField(blank=True, choices=[('mountain', 'Mountain Silence'), ('coastal', 'Coastal Escape'), ('culture', 'Culture & History'), ('nature', 'Nature & Wildlife')], help_text='Choose the travel mood for this destination.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], help_text='Choose the best travel season for this destination.', max_length=20, null=True),
        ),
    ]
