# Generated by Django 6.0 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0012_destination_destination_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Travel.destination'),
        ),
    ]
