# Generated by Django 6.0 on 2026-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0013_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base booking price per person', max_digits=10),
        ),
    ]
