# Generated by Django 6.0 on 2026-09-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0014_destination_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_price',
        ),
    ]
