# Generated by Django 6.0 on 2026-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0016_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=200, unique=True)),
                ('mood_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('mood_desc', models.TextField(blank=True, null=True)),
                ('mood_image', models.ImageField(blank=True, null=True, upload_to='moods/')),
                ('mood_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
