# Generated by Django 6.0 on 2026-09-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0017_tour_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='Travel.tour_mood'),
        ),
    ]
