# Generated by Django 6.0 on 2026-09-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0018_tour_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='mood',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_operator',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='train',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='train',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='train',
            name='railway_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buses/'),
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flights/'),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trains/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Travel.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Travel.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Travel.train'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Tour_Mood',
        ),
    ]
