# Generated by Django 6.0 on 2026-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0019_remove_tour_mood_rename_is_active_bus_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='train',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
